map_theme_main <- theme( panel.background = element_rect(fill="white"),
                         panel.border = element_rect(color="white", fill=NA, size=rel(1)),
                         axis.text.x = element_blank(),
                         axis.title.x = element_blank(),
                         axis.ticks.x = element_blank(),
                         axis.text.y = element_blank(),
                         axis.title.y = element_blank(),
                         plot.title = element_text(size = 16, hjust = 0.5),
                         #legend.position = "bottom",
                         #legend.justification = c(0,0),
                         legend.key = element_rect(fill = NA),
                         legend.background = element_blank(),
                         legend.text = element_text(size = 10),
                         legend.title = element_text(size = 12),
                         axis.ticks.y = element_blank(),
                         panel.grid = element_blank(),
                         plot.subtitle = element_text(hjust = 0.5),
                         legend.key.size = unit(1.2, 'cm'),
                         panel.grid.major = element_line(color = 'white'))